const express = require('express');
const authentController = require('../controller/authentController');
const authRouter = express.Router();

/**
 * @swagger
 * components:
 *    schema:
 *      Auth:
 *        type: object
 *        required:
 *          -id
 *          -name
 *          -email
 *          -password
 *        properties:
 *          id:
 *              type: string
 *              description: autogenerated by user Id
 *          name:
 *              type: string
 *              description: Names of the user
 *          email:
 *              type: string
 *              description:email of the user
 *          password:
 *              type: string
 *              description: Plain text password
 *        example:
 *          id: 3567846dd82cffa860074222
 *          name: Admin
 *          email: example@gmail.com
 *          password: password
 */


authRouter.get("/profile", authentController.profile);
authRouter.post("/admin/signup", authentController.signup);
/**
 * @swagger
 * tags:
 *  name: Auth
 *  description: Authentication APIs
 * /login:
 *  post:
 *   summary: Login user
 *   tags: [Auth]
 *   requestBody:
 *      required: true
 *      content:
 *        application/json:
 *          schema:
 *              type: object
 *              properties:
 *                email:
 *                  type: string
 *                password:
 *                  type: string
 *              example:
 *                email: example@gmail.com
 *                password: password
 *   responses:
 *    200:
 *      description: Login a user
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            properties:
 *                data:
 *                  type: object
 *                status:
 *                  type: integer
 *                message:
 *                  type: string
 *            example:
 *                data:
 *                   {
 *                       user: 6408579a4f512c67069166c1
 *                   }
 *                status: 200
 *                message: "logged in successfully"
 *    400:
 *      description: Authentication error
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            properties:
 *                errors:
 *                  type: object
 *                status:
 *                  type: integer
 *                message:
 *                  type: string
 *            example:
 *                errors: {
 *                      "name": "error message",
 *                       "email": "error message",
 *                       "password": "error message"
 *                   }
 *                status: 400
 *                message: "You're not logged in"
 */

authRouter.post("/login", authentController.login);

/**
 * @swagger
 * tags:
 *  name: Auth
 *  description: Authnetication APIs
 * /logout:
 *  post:
 *   summary: Logout user
 *   tags: [Auth]
 *   responses:
 *    200:
 *      description: Logout a user
 *      content:
 *        application/json:
 *          schema:
 *            type: object
 *            properties:
 *                status:
 *                  type: integer
 *                message:
 *                  type: string
 *            example:
 *                status: 200
 *                message: "Successfully logged out"
 */
authRouter.post("/logout", authentController.logout);

module.exports = authRouter;


 /**
   * @swagger
   * tags:
   *  name: Blog
   *  description: Blog managing APIs
   * /blogs/{id}:
   *  delete:
   *   summary: Delete a blog
   *   tags: [Blog]
   *   parameters:
   *     - name: id
   *       in: path
   *       required: true
   *       description: The ID of the blog to delete.
   *       schema:
   *         type: string
   *   responses:
   *    200:
   *      description: Deleted blog
   *      content:
   *        application/json:
   *          schema:
   *            type: object
   *            properties:
   *                data:
   *                  type: object
   *                status:
   *                  type: integer
   *                message:
   *                  type: string
   *            example:
   *                data:
   *                    {
   *                       "_id": "6408346dd82cffa860074200",
   *                      "title": "The blog name",
   *                     "content": "How are you?",
   *                    "likes": 2,
   *                       "thumbnail": "sdasdas",
   *                       "createdAt": "2020-02-08T07:08:29.851Z",
   *                       "updatedAt": "2022-02-08T07:08:29.851Z",
   *                       "__v": 0
   *                   }
   *
   *                status: 200
   *                message: "blog deleted successfully"
   *    400:
   *      description: Authorization error
   *      content:
   *        application/json:
   *          schema:
   *            type: object
   *            properties:
   *                status:
   *                  type: integer
   *                message:
   *                  type: string
   *            example:
   *                status: 400
   *                message: "You're not logged in"
   */